[config]
skip_core_tasks = true

[tasks.build]
description = "Build All"
dependencies = ["build-web"]

[tasks.build-web]
dependencies = ["replace_gstatic"]

[tasks.replace_gstatic]
dependencies = ["download-firebasejs"]
script = [
'''
#!/usr/bin/env bash
for src in build/web/*.js
do
    dst=${src}.replaced
    cat $src | sed 's/https:\/\/www\.gstatic\.com/./g' > $dst
    mv -vf $dst $src
done
'''
]

[tasks.download-firebasejs]
dependencies = ["build-chrome_extension"]
script = [
'''
version="8.10.1"
dstdir="build/web/firebasejs/$version"
mkdir -pv $dstdir
for mod in "app" "messaging"
do
    url="https://www.gstatic.com/firebasejs/${version}/firebase-${mod}.js"
    target=$dstdir/$(basename $url)
    echo "Downloading $url -> $target"
    curl -o $target -OL $url
done
'''
]

[tasks.build-chrome_extension]
script = [
'''
#!/usr/bin/env bash
flutter build web --web-renderer html --csp
'''
]
