[config]
skip_core_tasks = true

[tasks.build]
description = "Build All"
dependencies = ["build-web"]

[tasks.build-web]
dependencies = ["prepare-web"]
script = [
    '''
    flutter build web --web-renderer html
    '''
]

[tasks.build-android]
dependencies = ["codegen-bridge"]
script = [
    '''
    flutter build apk
    '''
]

[tasks.prepare-web]
dependencies = ["copy-wasm-web"]

[tasks.copy-wasm-web]
dependencies = ["build-wasm"]
script = [
    '''
    dir="web/generated/wasmlib"
    rm -rf $dir
    mkdir -pv $dir
    for ext in js wasm
    do
        cp -vf wasmlib/pkg/*.$ext $dir/
    done
    '''
]

[tasks.build-wasm]
dependencies = ["install-wasm-pack", "codegen-bridge"]
script = [
    '''
    cd wasmlib
    export AR=/usr/local/opt/llvm/bin/llvm-ar
    export CC=/usr/local/opt/llvm/bin/clang
    wasm-pack build --target web
    '''
]

[tasks.install-wasm-pack]
script = [
    '''
    type wasm-pack || (curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh)
    '''
]

[tasks.codegen-bridge]
dependencies = ["install-flutter_rust_bridge", "flutter-get"]
script = [
    '''
    cargo install cargo-ndk cbindgen

    flutter_rust_bridge_codegen \
        --rust-input wasmlib/src/api.rs \
        --dart-output lib/bridge_generated.dart

    flutter pub run build_runner build
    '''
]

[tasks.flutter-get]
script = [
    '''
    flutter pub get
    '''
]

[tasks.install-flutter_rust_bridge]
script = [
    '''
    cargo install flutter_rust_bridge_codegen
    dart pub global activate ffigen
    '''
]
