[config]
skip_core_tasks = true

[tasks.build]
description = "Build All"
dependencies = ["build-android"]

[tasks.build-android]
dependencies = ["prepare-android"]
script = [
    '''
    java -version # must be java 8, Zulu is recommended
    flutter build apk
    '''
]

[tasks.prepare-android]
dependencies = ["codegen-bridge"]
script = [
    '''
    rustup target add \
        aarch64-linux-android \
        armv7-linux-androideabi \
        x86_64-linux-android \
        i686-linux-android

    base="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/darwin-x86_64/lib64/clang/14.0.1/lib/linux"
    for dir in $(ls -d $base/*/)
    do
        echo "working on $dir"
        echo 'INPUT(-lunwind)' > $dir/libgcc.a
    done
    '''
]

[tasks.build-native]
dependencies = ["codegen-bridge"]
script = [
    '''
    cd native
    cargo build
    '''
]

[tasks.codegen-bridge]
dependencies = ["install-flutter_rust_bridge", "flutter-get", "clean-codegen-bridge"]
script = [
    '''
    cargo install cargo-ndk cbindgen

    flutter_rust_bridge_codegen \
        --rust-input native/src/api.rs \
        --dart-output lib/bridge_generated.dart \
        --verbose

    flutter pub run build_runner build
    '''
]

[tasks.clean-codegen-bridge]
dependencies = ["install-flutter_rust_bridge", "flutter-get"]
script = [
    '''
    for file in $(find . -name 'bridge_generated.*')
    do
        rm -vf $file
    done
    '''
]

[tasks.flutter-get]
script = [
    '''
    flutter pub get
    '''
]

[tasks.install-flutter_rust_bridge]
script = [
    '''
    cargo install flutter_rust_bridge_codegen --version 1.62.0
    dart pub global activate ffigen
    '''
]
