[config]
skip_core_tasks = true

[tasks.build]
description = "Build All"
dependencies = ["build-android"]

[tasks.build-android]
dependencies = ["codegen-bridge"]
script = [
    '''
    flutter build apk
    '''
]

[tasks.build-rust]
dependencies = ["codegen-bridge"]
script = [
    '''
    cd wasmlib
    export AR=/usr/local/opt/llvm/bin/llvm-ar
    export CC=/usr/local/opt/llvm/bin/clang
    wasm-pack build --target web
    '''
]

[tasks.codegen-bridge]
dependencies = ["install-flutter_rust_bridge", "flutter-get", "clean-codegen-bridge"]
script = [
    '''
    cargo install cargo-ndk cbindgen

    flutter_rust_bridge_codegen \
        --rust-input wasmlib/src/api.rs \
        --dart-output lib/bridge_generated.dart \
        --verbose

    flutter pub run build_runner build
    '''
]

[tasks.clean-codegen-bridge]
dependencies = ["install-flutter_rust_bridge", "flutter-get"]
script = [
    '''
    for file in $(find . -name 'bridge_generated.*')
    do
        rm -vf $file
    done
    '''
]

[tasks.flutter-get]
script = [
    '''
    flutter pub get
    '''
]

[tasks.install-flutter_rust_bridge]
script = [
    '''
    cargo install flutter_rust_bridge_codegen --version 1.62.0
    dart pub global activate ffigen
    '''
]
