name: Build
on: [push]

env:
  FLUTTER_VERSION: 3.7.0

jobs:
  build-android:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/.crates2.json
            ~/.cargo/.crates.toml
            ~/.cargo/git
            ~/.cargo/registry
            ./target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: flutter cache
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter

      - name: install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"

      - name: Install makers
        run: type makers || cargo install cargo-make

      - name: Install LLVM
        run: sudo apt-get install libclang-dev

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Install rust targets
        run: rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r24
          add-to-path: false
      - name: Set ANDROID_NDK
        run: echo "ANDROID_NDK=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV

      - name: Set ANDROID_NDK for gradle
        run: |
          mkdir ~/.gradle
          echo "ANDROID_NDK=$ANDROID_NDK" > ~/.gradle/gradle.properties

      - name: Hack Android NDK
        run: |
          find ${ANDROID_NDK} -name 'libunwind.a' | while read file
          do
            dir=$(dirname $file)
            echo "Adding $dir/libgcc.a"
            echo 'INPUT(-lunwind)' > $dir/libgcc.a
          done

      - uses: gradle/gradle-build-action@v2

      - name: build all
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: build-android

      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: android
          path: build/app/outputs/flutter-apk/app-release.apk
