name: Build
on: [push]

env:
  FLUTTER_VERSION: 2.10.5

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/.crates2.json
            ~/.cargo/.crates.toml
            ~/.cargo/git
            ~/.cargo/registry
            ./target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: flutter cache
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter

      - name: install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"

      - name: Install makers
        run: type makers || cargo install cargo-make

      - name: build all
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: build

      - name: Archive [Chrome Extension]
        uses: actions/upload-artifact@v2
        with:
          name: chrome-extension
          path: build/web