name: Build
on: [push]

env:
  FLUTTER_VERSION: 2.10.5

jobs:
  build-chrome_extension:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/.crates2.json
            ~/.cargo/.crates.toml
            ~/.cargo/git
            ~/.cargo/registry
            ./target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: flutter cache
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter

      - name: install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"

      - name: Install makers
        run: type makers || cargo install cargo-make

      - name: Install LLVM
        run: sudo apt-get install libclang-dev

      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: build-chrome_extension

      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: chrome-extension
          path: build/web

  build-android:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/.crates2.json
            ~/.cargo/.crates.toml
            ~/.cargo/git
            ~/.cargo/registry
            ./target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: flutter cache
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter

      - name: install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"

      - name: Install makers
        run: type makers || cargo install cargo-make

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r24
          add-to-path: false
      - name: Set ANDROID_NDK_HOME
        run: echo "ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV

      - uses: gradle/gradle-build-action@v2

      - name: build all
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: build-android

      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: android
          path: build/app/outputs/flutter-apk/app-release.apk
